### ISSUE TITLE
Weapons policy needs to be added to Syndicate and Citizen CoC websites

### ISSUE THREAD

**Issue by aeschright** [stumpsyn/policies#12]
There's a weapons policy that we added to the Citizen Code of Conduct, but it's not in the version on the websites.

**Comment by elea** [comment]
Updated via:
http://stumptownsyndicate.org/code-of-conduct/
http://citizencodeofconduct.org/
https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md

**Comment by 2x1tinkTink** [comment]
jah bless
