### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by yoshuawuyts** [stumpsyn/policies#23]
Hi, we noticed [the website](http://citizencodeofconduct.org/) is currently down, reported in https://github.com/rust-lang/www.rust-lang.org/issues/683. I'm not sure if you're aware, but letting you know just in case.

Thanks for running this project!

**Comment by micgro42** [comment]
The site is down again with the error message `Error establishing a database connection`

**Comment by cestanton** [comment]
We've implemented some changes to hopefully put an end to the recurring phenomenon of the site going down!

**Comment by ilyapopov** [comment]
And it is down again.
